#!/Library/Frameworks/Python.framework/Versions/3.12/bin/python3


import boto3
import requests
import os

s3 = boto3.client('s3', region_name='us-east-1')

os.environ["URL1"] = input('Paste URL here: ')
os.environ["h"] = requests.get(os.getenv("URL1"))
os.environ["FILE1"] = input('Insert File Name: ')
open(os.getenv("FILE1"),'wb').write(os.getenv("h").content)

bucket = 'ds2002-ngx3fy'
local_file = os.getenv("FILE1")

resp = s3.put_object(Body = local_file, Bucket = bucket, Key = local_file, ACL = 'public-read')

bucket_name = 'ds2002-ngx3fy'
object_name = os.getenv("FILE1")
expires_in = 604800

response = s3.generate_presigned_url('get_object', Params={'Bucket': bucket_name, 'Key': object_name}, ExpiresIn= expires_in )
